name: CI pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Clear npm cache
        run: npm cache clean --force  # Clear npm cache
      - name: Delete node_modules
        run: rm -rf node_modules  # Remove node_modules directory
      - name: Install dependencies
        run: npm install
      - name: Install TypeScript
        run: npm install typescript --save-dev
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Build
        run: npm run build
