name: build and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: subhadeepthandaka/leetcode-master:latest

      - name: Verify push
        run: docker pull subhadeepthandaka/leetcode-master:latest
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker pull subhadeepthandaka/leetcode-master:latest
            docker stop leetcode-master || true
            docker rm leetcode-master || true
            docker run -d -p 3000:3000 --name leetcode-master subhadeepthandaka/leetcode-master:latest
